import { FieldModal } from '@/components/FieldModal';
import { Colors, Radius, Shadows } from '@/constants/theme';
import { useApp } from '@/context/AppContext';
import { leaderMembers, leaderTrip } from '@/data/fieldOpsMock';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const checks = ['Đã đối soát đủ thiết bị với Staff Delivery', 'Đã kiểm tra y tế và thông tin liên hệ khẩn cấp', 'GPS vệ tinh đã khóa vị trí tuyến', 'Tất cả thành viên đã đọc quy tắc an toàn'];

export default function LeaderPretripScreen() {
  const router = useRouter();
  const { approveLeaderPretrip, fieldWorkflow, setLeaderMemberAttendance } = useApp();
  const [done, setDone] = useState(checks.map(() => false));
  const [modal, setModal] = useState(false);
  const [isApproving, setIsApproving] = useState(false);
  const members = useMemo(() => leaderMembers.map(member => ({
    ...member,
    attendance: fieldWorkflow.leaderAttendance.find(item => item.memberName === member.name)?.status ?? 'PENDING',
  })), [fieldWorkflow.leaderAttendance]);
  const processedMembers = members.every(member => member.attendance !== 'PENDING');
  const ready = done.every(Boolean) && processedMembers;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>
    <Header onBack={() => router.back()} /><Text style={styles.eyebrow}>LEADER OPERATION · PRE-TRIP</Text><Text style={styles.title}>Khóa quyền bắt đầu chuyến</Text><Text style={styles.meta}>{leaderTrip.name} · {leaderTrip.date}</Text>
    <View style={[styles.status, ready && styles.statusReady]}><Ionicons name={ready ? 'lock-open' : 'lock-closed'} size={23} color={ready ? Colors.primaryDark : '#9b6700'} /><View style={{ flex: 1 }}><Text style={styles.statusTitle}>{ready ? 'Đã đủ điều kiện điều hành' : 'Chưa đủ điều kiện bắt đầu'}</Text><Text style={styles.statusText}>{ready ? 'Access lock đã mở, GPS session có thể khởi tạo.' : 'Hoàn tất checklist và quân số để mở khóa.'}</Text></View></View>
    <Text style={styles.section}>CHECKLIST BẮT BUỘC</Text><View style={styles.card}>{checks.map((label, index) => <CheckRow key={label} label={label} checked={done[index]} onPress={() => setDone(current => current.map((value, currentIndex) => currentIndex === index ? !value : value))} />)}</View>
    <Text style={styles.section}>QUÂN SỐ CHECK-IN · {members.filter(member => member.attendance === 'CHECKED_IN').length}/{members.length}</Text><View style={styles.card}>{members.map(member => <View style={styles.member} key={member.name}><View style={[styles.dot, member.attendance !== 'CHECKED_IN' && styles.wait]} /><Text style={styles.memberName}>{member.name}</Text><Text style={styles.memberStatus}>{member.attendance === 'CHECKED_IN' ? 'Đã check-in' : member.attendance === 'NO_SHOW' ? 'No-show' : 'Chờ xử lý'}</Text>{member.attendance === 'PENDING' && <View style={styles.attendanceActions}><TouchableOpacity onPress={() => setLeaderMemberAttendance(member.name, 'CHECKED_IN')}><Ionicons name="checkmark-circle-outline" size={21} color={Colors.primaryDark} /></TouchableOpacity><TouchableOpacity onPress={() => setLeaderMemberAttendance(member.name, 'NO_SHOW')}><Ionicons name="close-circle-outline" size={21} color="#b44638" /></TouchableOpacity></View>}</View>)}</View>
    {!ready && <Text style={styles.lockReason}>{done.every(Boolean) ? 'Cần xử lý trạng thái của toàn bộ thành viên bằng check-in hoặc no-show.' : 'Cần hoàn tất checklist và xử lý toàn bộ thành viên.'}</Text>}
    <TouchableOpacity disabled={!ready || isApproving} style={[styles.primary, (!ready || isApproving) && styles.disabled]} onPress={() => { setIsApproving(true); setTimeout(() => { approveLeaderPretrip(); setIsApproving(false); setModal(true); }, 500); }}><Ionicons name="play" size={17} color="#fff" /><Text style={styles.primaryText}>{isApproving ? 'ĐANG MỞ KHÓA...' : fieldWorkflow.leaderPretripApproved ? 'ĐÃ MỞ KHÓA & TIẾP TỤC ĐIỀU HÀNH' : 'MỞ KHÓA & BẮT ĐẦU ĐIỀU HÀNH'}</Text></TouchableOpacity>
  </ScrollView><FieldModal visible={modal} title="Đã mở khóa chuyến đi" message="Bảng điều hành GPS và quyền xác nhận checkpoint đã được kích hoạt cho Mountain Leader." icon="lock-open" actionLabel="Mở bản đồ GPS" onAction={() => { setModal(false); router.push('/field-operations/leader-map'); }} onClose={() => setModal(false)} /></SafeAreaView>;
}
function Header({ onBack }: { onBack: () => void }) { return <View style={styles.header}><TouchableOpacity onPress={onBack}><Ionicons name="arrow-back" size={23} color={Colors.ink} /></TouchableOpacity><Text style={styles.headerTitle}>Pre-trip access lock</Text><View style={{ width: 23 }} /></View>; }
function CheckRow({ label, checked, onPress }: { label: string; checked: boolean; onPress: () => void }) { return <TouchableOpacity style={styles.check} onPress={onPress}><View style={[styles.checkbox, checked && styles.checked]}>{checked && <Ionicons name="checkmark" size={14} color="#fff" />}</View><Text style={styles.checkText}>{label}</Text></TouchableOpacity>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.surface }, content: { padding: 20, paddingBottom: 35 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 27 }, headerTitle: { color: Colors.ink, fontWeight: '800' }, eyebrow: { color: Colors.primaryDark, fontSize: 11, fontWeight: '800', letterSpacing: .8 }, title: { color: Colors.ink, fontSize: 27, fontWeight: '800', marginTop: 8 }, meta: { color: Colors.onSurfaceMuted, marginTop: 5 }, status: { flexDirection: 'row', gap: 12, padding: 16, borderRadius: Radius.md, backgroundColor: '#fff3d2', marginTop: 20 }, statusReady: { backgroundColor: '#e9f4de' }, statusTitle: { color: Colors.ink, fontWeight: '800' }, statusText: { color: Colors.body, fontSize: 12, marginTop: 4 }, section: { color: Colors.onSurfaceMuted, fontSize: 11, fontWeight: '800', letterSpacing: .8, marginTop: 24, marginBottom: 10 }, card: { backgroundColor: '#fff', borderRadius: Radius.md, paddingHorizontal: 16, ...Shadows.card }, check: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: Colors.surfaceContainer }, checkbox: { width: 22, height: 22, borderRadius: 5, borderWidth: 1, borderColor: Colors.onSurfaceMuted, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: Colors.primaryDark, borderColor: Colors.primaryDark }, checkText: { color: Colors.ink, fontSize: 13, flex: 1 }, member: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: Colors.surfaceContainer }, dot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#25a55a' }, wait: { backgroundColor: '#e7a900' }, memberName: { flex: 1, color: Colors.ink, fontWeight: '700' }, memberStatus: { color: Colors.onSurfaceMuted, fontSize: 11 }, attendanceActions: { flexDirection: 'row', gap: 8 }, lockReason: { color: '#9b6700', fontSize: 12, marginTop: 10 }, primary: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, backgroundColor: Colors.primaryDark, padding: 15, borderRadius: Radius.sm, marginTop: 24 }, disabled: { backgroundColor: '#aab3a5' }, primaryText: { color: '#fff', fontWeight: '800', fontSize: 12 } });