import { Colors, Radius, Shadows } from '@/constants/theme';
import { FieldModal } from '@/components/FieldModal';
import { leaderMembers, leaderTrip } from '@/data/fieldOpsMock';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function LeaderTripScreen() { const router = useRouter(); const [checked, setChecked] = useState(leaderTrip.checkedIn); const [started, setStarted] = useState(false); return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Header onBack={() => router.back()} /><Text style={styles.eyebrow}>TRIP OPERATIONS</Text><Text style={styles.title}>{leaderTrip.name}</Text><Text style={styles.meta}>{leaderTrip.code} · {leaderTrip.date}</Text><View style={styles.hero}><View><Text style={styles.heroLabel}>CHECK-IN ĐOÀN</Text><Text style={styles.heroValue}>{checked}/{leaderTrip.members}</Text></View><View style={styles.progress}><View style={[styles.progressFill, { width: `${(checked / leaderTrip.members) * 100}%` }]} /></View><Text style={styles.heroHint}>Cần xác nhận đủ thành viên trước khi bắt đầu trek.</Text></View><Text style={styles.section}>THÀNH VIÊN & CHECKPOINT</Text><View style={styles.card}>{leaderMembers.map((member, index) => <View key={member.name} style={styles.member}><View style={[styles.dot, member.status === 'Chờ check-in' && styles.wait]} /><View style={{ flex: 1 }}><Text style={styles.memberName}>{member.name}</Text><Text style={styles.memberRole}>{member.role}</Text></View><Text style={styles.memberStatus}>{member.status}</Text>{member.status === 'Chờ check-in' && <TouchableOpacity onPress={() => setChecked(value => value + 1)}><Ionicons name="checkmark-circle-outline" size={22} color={Colors.primaryDark} /></TouchableOpacity>}</View>)}</View><Text style={styles.section}>GPS SESSION</Text><TouchableOpacity style={styles.feature} onPress={() => router.push('/field-operations/leader-map')}><Ionicons name="navigate-circle" size={25} color={Colors.primaryDark} /><View style={{ flex: 1 }}><Text style={styles.featureTitle}>Theo dõi tuyến và checkpoint</Text><Text style={styles.featureText}>CP03 · Độ cao hiện tại {leaderTrip.altitude}</Text></View><Ionicons name="chevron-forward" size={18} color={Colors.onSurfaceMuted} /></TouchableOpacity><TouchableOpacity style={styles.primary} onPress={() => setStarted(true)}><Text style={styles.primaryText}>BẮT ĐẦU CHUYẾN ĐI</Text><Ionicons name="play" size={17} color="#fff" /></TouchableOpacity></ScrollView><FieldModal visible={started} title="Trip đã bắt đầu" message="GPS session và chế độ theo dõi thành viên đã được kích hoạt." icon="navigate-circle" actionLabel="Mở bản đồ GPS" onAction={() => { setStarted(false); router.push('/field-operations/leader-map'); }} onClose={() => setStarted(false)} /></SafeAreaView>; }
function Header({ onBack }: { onBack: () => void }) { return <View style={styles.header}><TouchableOpacity onPress={onBack}><Ionicons name="arrow-back" size={23} color={Colors.ink} /></TouchableOpacity><Text style={styles.headerTitle}>Bảng điều khiển</Text><Ionicons name="ellipsis-horizontal" size={22} color={Colors.ink} /></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.surface }, content: { padding: 20, paddingBottom: 35 }, header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 30 }, headerTitle: { fontWeight: '800', color: Colors.ink }, eyebrow: { fontSize: 11, color: Colors.primaryDark, fontWeight: '800', letterSpacing: 1 }, title: { fontSize: 28, color: Colors.ink, fontWeight: '800', marginTop: 8 }, meta: { color: Colors.onSurfaceMuted, marginTop: 5 }, hero: { backgroundColor: Colors.inverseSurface, padding: 18, borderRadius: Radius.md, marginTop: 20, ...Shadows.tactical }, heroLabel: { color: Colors.primary, fontSize: 11, fontWeight: '800' }, heroValue: { color: '#fff', fontSize: 38, fontWeight: '800', marginTop: 5 }, progress: { height: 7, backgroundColor: '#425340', borderRadius: 4, marginTop: 14 }, progressFill: { height: 7, backgroundColor: Colors.primary, borderRadius: 4 }, heroHint: { color: '#c1d0bd', fontSize: 12, marginTop: 10 }, section: { color: Colors.onSurfaceMuted, fontSize: 11, fontWeight: '800', letterSpacing: .8, marginTop: 25, marginBottom: 10 }, card: { backgroundColor: '#fff', borderRadius: Radius.md, paddingHorizontal: 16, ...Shadows.card }, member: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: Colors.surfaceContainer, gap: 10 }, dot: { width: 9, height: 9, borderRadius: 5, backgroundColor: '#25a55a' }, wait: { backgroundColor: '#e7a900' }, memberName: { color: Colors.ink, fontWeight: '700', fontSize: 14 }, memberRole: { color: Colors.onSurfaceMuted, fontSize: 11, marginTop: 2 }, memberStatus: { color: Colors.onSurfaceMuted, fontSize: 11 }, feature: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, backgroundColor: '#eaf5e1', borderRadius: Radius.sm }, featureTitle: { color: Colors.ink, fontWeight: '800' }, featureText: { color: Colors.body, fontSize: 12, marginTop: 4 }, primary: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, backgroundColor: Colors.primaryDark, borderRadius: Radius.sm, padding: 15, marginTop: 24 }, primaryText: { color: '#fff', fontWeight: '800' } });