import { FieldModal } from '@/components/FieldModal';
import { Colors, Radius, Shadows } from '@/constants/theme';
import { useApp } from '@/context/AppContext';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function LeaderSummaryScreen() { const router = useRouter(); const [complete, setComplete] = React.useState(false); const { completeLeaderTrip, sendLeaderReport, fieldWorkflow } = useApp(); return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><Ionicons name="arrow-back" size={23} color={Colors.ink} /></TouchableOpacity><Text style={styles.headerTitle}>Tổng kết & nghiệm thu</Text><View style={{ width: 23 }} /></View><View style={styles.success}><Ionicons name="checkmark-circle" size={42} color={Colors.primary} /><Text style={styles.successTitle}>{fieldWorkflow.leaderReportSent ? 'ĐÃ GỬI BÁO CÁO CHỜ ĐỐI SOÁT' : 'CHUYẾN ĐI SẴN SÀNG CHỐT'}</Text><Text style={styles.successText}>Tất cả checkpoint và bằng chứng hiện trường đã được đồng bộ.</Text></View><View style={styles.card}>{[['Thành viên hoàn tất', '6/6'], ['Checkpoint đã ghi nhận', '05/05'], ['Quãng đường thực tế', '16.2 km'], ['Sự cố đang mở', '0']].map(([label, value]) => <View style={styles.row} key={label}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}</View><Text style={styles.section}>BẰNG CHỨNG HIỆN TRƯỜNG</Text><View style={styles.evidence}><Ionicons name="images-outline" size={28} color={Colors.primaryDark} /><View style={{ flex: 1 }}><Text style={styles.evidenceTitle}>12 ảnh · 3 biên bản</Text><Text style={styles.label}>Đã phân loại theo checkpoint</Text></View><Ionicons name="checkmark-circle" size={21} color={Colors.primaryDark} /></View><TouchableOpacity style={styles.primary} onPress={() => { completeLeaderTrip(); sendLeaderReport(); setComplete(true); }}><Text style={styles.primaryText}>{fieldWorkflow.leaderReportSent ? 'ĐÃ GỬI BÁO CÁO' : 'XÁC NHẬN HOÀN TẤT CHUYẾN'}</Text><Ionicons name="arrow-forward" size={17} color="#fff" /></TouchableOpacity></ScrollView><FieldModal visible={complete} title="Đã hoàn tất chuyến" message="Báo cáo đã khóa. Task thu hồi RET-1182 đã được mở cho Staff Delivery." icon="checkmark-circle" actionLabel="Về dashboard" onAction={() => { setComplete(false); router.replace('/field-operations'); }} onClose={() => setComplete(false)} /></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: Colors.surface }, content: { padding: 20, paddingBottom: 35 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 }, headerTitle: { color: Colors.ink, fontSize: 17, fontWeight: '800' }, success: { backgroundColor: Colors.inverseSurface, borderRadius: Radius.md, padding: 22, alignItems: 'center' }, successTitle: { color: Colors.primary, fontSize: 16, fontWeight: '800', marginTop: 12 }, successText: { color: '#c1d0bd', fontSize: 13, lineHeight: 19, textAlign: 'center', marginTop: 7 }, card: { backgroundColor: '#fff', borderRadius: Radius.md, padding: 17, marginTop: 18, ...Shadows.card }, row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: Colors.surfaceContainer }, label: { color: Colors.onSurfaceMuted, fontSize: 13 }, value: { color: Colors.ink, fontWeight: '800', fontSize: 14 }, section: { color: Colors.onSurfaceMuted, fontSize: 11, fontWeight: '800', letterSpacing: .8, marginTop: 25, marginBottom: 10 }, evidence: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#eaf5e1', borderRadius: Radius.sm, padding: 16 }, evidenceTitle: { color: Colors.ink, fontWeight: '800', marginBottom: 4 }, primary: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, backgroundColor: Colors.primaryDark, borderRadius: Radius.sm, padding: 15, marginTop: 25 }, primaryText: { color: '#fff', fontSize: 13, fontWeight: '800' } });